spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true

  data:
    mongodb:
      host: 192.168.0.15
      port: 27017
      username: testuser
      password: testuser
      database: e-commerce

  mongodb:
    embedded:
      version: 4.4.13
