spring:
  webflux:
    hiddenmethod:
      filter:
        enabled: true

  data:
    mongodb:
      host:
      port:
      username:
      password:
      database:

  mongodb:
    embedded:
      version: 4.4.13
